# -*- coding: utf-8 -*-
"""Meeting Minutes Generator Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bmn5z0FYnXV1hx9pD9F6TlBvVTcXF_MX
"""

import pandas as pd
from datetime import datetime

print("MEETING MINUTES GENERATOR\n")

#user Input
meeting_title= input("enter meeting title:")
date=input("enter meeting date(DD-MM-YYYY):")
time=input("enter meeting time:")
participants=input("enter participants(comma separated):")
participants =input("enter agenda points(comma separated):")
decisions=input("enter decision taken(comma separated):")
action_items=input("enter action items(comma separated):")
prepared_by=input("prepared by:")

#process Inputs
participants_list=[p.strip() for p in participants.split(",") if p.strip()]
agenda_list=[a.strip() for a in agenda.split(",") if a.strip()]
decisions_list=[d.strip() for d in decisions.split(",") if d.strip()]
actions_list=[a.strip() for a in action_items.split(",") if a.strip()]
#Create structured meeting minutes
minutes={
    "Meeting Title":meeting_title,
    "Date":date,
    "Time":time,
    "participants":", ".join(participants_list),
    "Agenda":"; ".join(agenda_list),
    "Decision Taken":"; ".join(decisions_list),
    "Action Items":"; ".join(actions_list),
    "Prepared By":prepared_by,
    "Generated on": datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}
#Convert to DataFrame
df=pd.DataFrame(list(minutes.items()),columns=["Field","Details"])

print("\nGEnerated SucessFUlly")
display(df)

#Save as csv
df.to_csv("meting",index=False)
print("\n file saved.csv")

