# -*- coding: utf-8 -*-
"""Product Review Summarizer Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o_PDxDsL8hq4bek1ysctaJkyD16BeZcF
"""

!pip install transformers torch pandas

from transformers import pipeline
import pandas as pd

sentiment=pipeline("sentiment-analysis")
reviews="""The laptop starts quickly and work smoothly for daily tasks.
The scren quality is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when manyb apps are running.
Overall, its all good laptop for students but not for gaming."""
sentences = reviews.split(".")
pros=[]
cons=[]
for s in sentences:
    s=s.strip()
    if  s == "":
         continue
    result=sentiment(s)[0]
    if result["label"] == "POSITIVE":
         pros.append(s)
    elif result["label"] == "NEGATIVE":
         cons.append(s)
pros=pros[:1]
cons=cons[:1]
df=pd.DataFrame({
    "Pros": pros,
    "Cons": cons
})
df

