# -*- coding: utf-8 -*-
"""Sentence Similarity Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKUQ69rldSOprzRZBA_p4rQcYwvz2JkC
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util

model =SentenceTransformer('all-MiniLM-L6-v2')
text1=input("enter text 1: ")
text2=input("enter text 2: ")

embedding1 = model.encode(text1)
embedding2 = model.encode(text2)

Similarity = util.cos_sim(embedding1,embedding2)
print("\n similarity score:",round(float(Similarity),2))
if Similarity>0.75:
  print("similarity level:HIGH")
elif Similarity>0.4:
  print("similarity level:MEDIUM")
else:
  print("similarity level:LOW")