# -*- coding: utf-8 -*-
"""Text Generation Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOPOJJ54-JpV0UGcSHbm4umP_v0unNlB
"""

!pip install transformers torch

from transformers import pipeline
#load text generation model(Gen AI)
generator=pipeline(
    "text-generation",
    model="gpt2"
)
prompt="Artificial intelligence in finance will"

result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI generatedtext:")
print(result[0]['generated_text'])